apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lifehacker-frontend-deploy
  name: lifehacker-frontend-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: lifehacker-frontend-deploy
  type: ClusterIP
status:
  loadBalancer: {}